"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type View = "Overview" | "My Tasks" | "Study Planner" | "Focus Room" | "Notes" | "Settings";
type Task = { id: string; title: string; subject: string; date: string; plannedMinutes: number; completed: boolean; completedAt?: string; color: string };
type FocusSession = { id: string; completedAt: string; durationMinutes: number };
type PlannerData = Record<string, { goal: string; minutes: number }>;
type StoredData = { tasks: Task[]; sessions: FocusSession[]; planner: PlannerData; name: string; theme: "light" | "warm" };

const STORAGE_KEY = "studyforge-v2";
const colors = ["coral", "mint", "lavender", "yellow", "blue"];
const dateKey = (date: Date) => { const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60 * 1000).toISOString().slice(0, 10); };
const todayKey = () => dateKey(new Date());
const formatDate = (value: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(`${value}T12:00:00`));
const initials = (name: string) => name.trim().split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase() || "ST";
const emptyStoredData: StoredData = { tasks: [], sessions: [], planner: {}, name: "Student", theme: "light" };

function safeStoredData(): StoredData { try { const saved = localStorage.getItem(STORAGE_KEY); if (!saved) return emptyStoredData; const parsed = JSON.parse(saved) as Partial<StoredData>; return { ...emptyStoredData, ...parsed, tasks: parsed.tasks ?? [], sessions: parsed.sessions ?? [], planner: parsed.planner ?? {} }; } catch { return emptyStoredData; } }
function ProgressRing({ value }: { value: number }) { return <div className="progress-ring" style={{ "--progress": `${value * 3.6}deg` } as React.CSSProperties}><span>{value}%</span></div>; }
function SectionHeading({ eyebrow, title, action, onAction }: { eyebrow: string; title: string; action?: string; onAction?: () => void }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action && <button className="text-button" onClick={onAction}>{action} <span>↗</span></button>}</div>; }

function TaskForm({ onAdd, initialDate }: { onAdd: (task: Omit<Task, "id" | "completed" | "color">) => void; initialDate: string }) {
  const [title, setTitle] = useState(""); const [subject, setSubject] = useState(""); const [date, setDate] = useState(initialDate); const [minutes, setMinutes] = useState("30");
  const submit = (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; onAdd({ title: title.trim(), subject: subject.trim() || "General", date, plannedMinutes: Math.max(5, Number(minutes) || 30) }); setTitle(""); setSubject(""); setMinutes("30"); };
  return <form className="task-form" onSubmit={submit}><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="What do you want to study?" aria-label="Task title" /><input value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="Subject" aria-label="Task subject" /><input type="date" value={date} onChange={(event) => setDate(event.target.value)} aria-label="Task date" /><input className="minutes-input" type="number" min="5" step="5" value={minutes} onChange={(event) => setMinutes(event.target.value)} aria-label="Planned minutes" /><button type="submit">Add task <span>+</span></button></form>;
}
function TaskRow({ task, onToggle, onDelete }: { task: Task; onToggle: () => void; onDelete: () => void }) { return <div className={`task-row ${task.completed ? "is-done" : ""}`}><button className={`checkmark ${task.color}`} onClick={onToggle} aria-label={task.completed ? "Mark task incomplete" : "Mark task complete"}>{task.completed && "✓"}</button><span className="task-info"><strong>{task.title}</strong><span>{task.subject} · {formatDate(task.date)} · {task.plannedMinutes} min</span></span><button className="delete-task" onClick={onDelete} aria-label={`Delete ${task.title}`}>×</button></div>; }

export default function Home() {
  const [view, setView] = useState<View>("Overview"); const [tasks, setTasks] = useState<Task[]>([]); const [sessions, setSessions] = useState<FocusSession[]>([]); const [planner, setPlanner] = useState<PlannerData>({}); const [name, setName] = useState("Student"); const [theme, setTheme] = useState<"light" | "warm">("light"); const [selectedDay, setSelectedDay] = useState(todayKey()); const [timer, setTimer] = useState(25 * 60); const [timerRunning, setTimerRunning] = useState(false); const [hydrated, setHydrated] = useState(false); const hasHydrated = useRef(false);
  useEffect(() => { const restore = window.setTimeout(() => { const data = safeStoredData(); setTasks(data.tasks); setSessions(data.sessions); setPlanner(data.planner); setName(data.name); setTheme(data.theme); const savedTimer = localStorage.getItem("studyforge-timer"); if (savedTimer) { try { const parsed = JSON.parse(savedTimer) as { seconds: number; savedAt: number; running: boolean }; const elapsed = parsed.running ? Math.floor((Date.now() - parsed.savedAt) / 1000) : 0; setTimer(Math.max(0, parsed.seconds - elapsed)); setTimerRunning(parsed.running && parsed.seconds > elapsed); } catch { /* use defaults */ } } hasHydrated.current = true; setHydrated(true); }, 0); return () => window.clearTimeout(restore); }, []);
  useEffect(() => { if (hasHydrated.current) localStorage.setItem(STORAGE_KEY, JSON.stringify({ tasks, sessions, planner, name, theme } satisfies StoredData)); }, [tasks, sessions, planner, name, theme]);
  useEffect(() => { if (hasHydrated.current) localStorage.setItem("studyforge-timer", JSON.stringify({ seconds: timer, savedAt: Date.now(), running: timerRunning })); }, [timer, timerRunning]);
  useEffect(() => { if (!timerRunning) return; const interval = window.setInterval(() => setTimer((current) => current > 0 ? current - 1 : 0), 1000); return () => window.clearInterval(interval); }, [timerRunning]);
  useEffect(() => { if (timer === 0 && timerRunning) completeSession(); }, [timer, timerRunning]);
  const today = todayKey(); const currentDate = new Date(`${selectedDay}T12:00:00`); const weekStart = new Date(currentDate); weekStart.setDate(currentDate.getDate() - ((currentDate.getDay() + 6) % 7)); const week = Array.from({ length: 7 }, (_, index) => { const day = new Date(weekStart); day.setDate(weekStart.getDate() + index); return { key: dateKey(day), label: new Intl.DateTimeFormat("en-US", { weekday: "short" }).format(day).toUpperCase(), date: day.getDate() }; });
  const completedTasks = tasks.filter((task) => task.completed).length; const todaySessions = sessions.filter((session) => session.completedAt.slice(0, 10) === today); const todayFocus = todaySessions.reduce((sum, session) => sum + session.durationMinutes, 0); const completionRate = tasks.length ? Math.round((completedTasks / tasks.length) * 100) : 0; const weekSessions = sessions.filter((session) => week.some((day) => day.key === session.completedAt.slice(0, 10))); const streak = useMemo(() => { const activeDays = new Set(sessions.map((session) => session.completedAt.slice(0, 10)).concat(tasks.filter((task) => task.completed && task.completedAt).map((task) => task.completedAt!.slice(0, 10)))); let count = 0; const cursor = new Date(); while (activeDays.has(dateKey(cursor))) { count++; cursor.setDate(cursor.getDate() - 1); } return count; }, [sessions, tasks]);
  const selectedTasks = tasks.filter((task) => task.date === selectedDay); const timeLabel = `${String(Math.floor(timer / 60)).padStart(2, "0")}:${String(timer % 60).padStart(2, "0")}`; const dateLabel = new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" }).format(new Date());
  function addTask(input: Omit<Task, "id" | "completed" | "color">) { setTasks((current) => [...current, { ...input, id: crypto.randomUUID(), completed: false, color: colors[current.length % colors.length] }]); }
  function toggleTask(id: string) { setTasks((current) => current.map((task) => task.id === id ? { ...task, completed: !task.completed, completedAt: !task.completed ? new Date().toISOString() : undefined } : task)); }
  function deleteTask(id: string) { setTasks((current) => current.filter((task) => task.id !== id)); }
  function completeSession() { setSessions((current) => [...current, { id: crypto.randomUUID(), completedAt: new Date().toISOString(), durationMinutes: 25 }]); setTimer(25 * 60); setTimerRunning(false); }
  function renderTaskList(list: Task[], empty: string) { return list.length ? <div className="task-list">{list.map((task) => <TaskRow key={task.id} task={task} onToggle={() => toggleTask(task.id)} onDelete={() => deleteTask(task.id)} />)}</div> : <div className="empty-state"><span>✦</span><strong>{empty}</strong><p>Your saved activity will appear here.</p></div>; }
  if (!hydrated) return <main className="app-shell loading-shell"><div className="loading-mark">✦</div></main>;
  const navItems: { label: View; icon: string }[] = [{ label: "Overview", icon: "◈" }, { label: "My Tasks", icon: "✓" }, { label: "Study Planner", icon: "▦" }, { label: "Focus Room", icon: "◷" }, { label: "Notes", icon: "♧" }, { label: "Settings", icon: "⚙" }];
  return <main className={`app-shell ${theme === "warm" ? "warm-theme" : ""}`}><aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><span>study<span>forge</span></span></div><div className="profile"><div className="avatar">{initials(name)}</div><div><strong>{name}</strong><span>Student account</span></div><span className="profile-dot" /></div><nav className="main-nav" aria-label="Main navigation">{navItems.slice(0, 4).map((item) => <button key={item.label} className={view === item.label ? "nav-item active" : "nav-item"} onClick={() => setView(item.label)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-bottom"><p className="nav-label">YOUR SPACE</p>{navItems.slice(4).map((item) => <button key={item.label} className={view === item.label ? "nav-item active" : "nav-item"} onClick={() => setView(item.label)}><span>{item.icon}</span>{item.label}</button>)}<div className="upgrade-card"><span className="spark">✦</span><strong>Make every session count.</strong><p>Build a study rhythm that sticks.</p><button onClick={() => setView("Focus Room")}>Open Focus Room <span>→</span></button></div></div><div className="sidebar-foot"><span>?</span><span>Help center</span><span className="sidebar-version">v2.0</span></div></aside><section className="content-area"><header className="topbar"><div className="mobile-brand"><span className="brand-mark">✦</span> studyforge</div><div className="date-line"><span className="date-sun">☼</span><span>{dateLabel}</span></div><div className="top-actions"><div className="mini-avatar">{initials(name)}</div></div></header><div className="dashboard-wrap"><div className="welcome"><div><p className="eyebrow">{new Intl.DateTimeFormat("en-US", { weekday: "long" }).format(new Date()).toUpperCase()} · YOUR SPACE</p><h1>{view === "Overview" ? `StudyForge — Your Personal Study Command Center` : view}<span>✦</span></h1><p className="welcome-copy">{view === "Overview" ? "A little progress each day adds up to big results." : "Keep your next meaningful step in sight."}</p></div><button className="today-button" onClick={() => { setSelectedDay(today); setView("Overview"); }}>Today <span>⌄</span></button></div>
  {view === "Overview" && <><div className="stat-strip"><div><span className="stat-icon orange">◷</span><div><strong>{Math.floor(todayFocus / 60)}h {todayFocus % 60}m</strong><span>Focus time today</span></div></div><div><span className="stat-icon blue">✓</span><div><strong>{completedTasks} / {tasks.length}</strong><span>Tasks completed</span></div></div><div><span className="stat-icon purple">↗</span><div><strong>{completionRate}%</strong><span>Task completion</span></div></div><div><span className="stat-icon green">✦</span><div><strong>{streak} days</strong><span>Current streak</span></div></div></div><div className="dashboard-grid"><section className="panel tasks-panel"><SectionHeading eyebrow="YOUR DAY" title="Today's tasks" action="View all" onAction={() => setView("My Tasks")} />{renderTaskList(tasks.filter((task) => task.date === today).slice(0, 4), "No tasks planned for today")}</section><FocusPanel timer={timer} timeLabel={timeLabel} running={timerRunning} onToggle={() => setTimerRunning((running) => !running)} onReset={() => { setTimer(25 * 60); setTimerRunning(false); }} onComplete={completeSession} /></div><div className="dashboard-grid lower-grid"><PlannerPanel week={week} selectedDay={selectedDay} setSelectedDay={setSelectedDay} tasks={tasks} planner={planner} /><StatsPanel completionRate={completionRate} sessions={weekSessions} /></div><AISection /></>}
  {view === "My Tasks" && <section className="panel full-panel"><SectionHeading eyebrow="YOUR WORKLOAD" title="My tasks" /><TaskForm onAdd={addTask} initialDate={today} />{renderTaskList(tasks, "No tasks yet")}</section>}
  {view === "Study Planner" && <section className="panel full-panel"><SectionHeading eyebrow="PLAN YOUR WEEK" title="Study planner" /><PlannerPanel week={week} selectedDay={selectedDay} setSelectedDay={setSelectedDay} tasks={tasks} planner={planner} /><div className="planner-day-detail"><div><p className="eyebrow">{formatDate(selectedDay)}</p><h3>{selectedTasks.length ? `${selectedTasks.length} planned ${selectedTasks.length === 1 ? "task" : "tasks"}` : "A clear day"}</h3></div><TaskForm onAdd={addTask} initialDate={selectedDay} /></div>{renderTaskList(selectedTasks, "Nothing planned for this day")}</section>}
  {view === "Focus Room" && <section className="focus-view"><FocusPanel timer={timer} timeLabel={timeLabel} running={timerRunning} onToggle={() => setTimerRunning((running) => !running)} onReset={() => { setTimer(25 * 60); setTimerRunning(false); }} onComplete={completeSession} /><section className="panel session-history"><SectionHeading eyebrow="YOUR LOG" title="Completed sessions" />{sessions.length ? sessions.slice().reverse().map((session) => <div className="history-row" key={session.id}><span className="history-icon">◷</span><span><strong>{session.durationMinutes} minute focus session</strong><small>{new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(session.completedAt))}</small></span></div>) : <div className="empty-state"><span>◷</span><strong>No completed sessions yet</strong><p>Finish a focus block to start your log.</p></div>}</section></section>}
  {view === "Notes" && <section className="panel full-panel simple-page"><span className="page-icon">♧</span><SectionHeading eyebrow="YOUR SPACE" title="Notes" /><p className="page-description">A dedicated notes workspace is coming next. For now, keep your study plan focused on tasks and sessions.</p><div className="coming-state">Notes will live here when you&apos;re ready to capture them.</div></section>}
  {view === "Settings" && <Settings name={name} setName={setName} theme={theme} setTheme={setTheme} />}<footer className="dashboard-footer"><span>StudyForge · Your personal learning space</span><span>Built for meaningful progress <span className="footer-star">✦</span></span></footer></div></section></main>;
}

function FocusPanel({ timer, timeLabel, running, onToggle, onReset, onComplete }: { timer: number; timeLabel: string; running: boolean; onToggle: () => void; onReset: () => void; onComplete: () => void }) { return <section className="panel focus-panel"><div className="focus-top"><div><p className="eyebrow">FOCUS ROOM</p><h2>{running ? "Stay with it" : timer < 25 * 60 ? "Paused for now" : "Time to focus"}</h2><p>One clear block. One meaningful win.</p></div><span className="focus-sun">☼</span></div><div className="timer"><span className="timer-label">{running ? "FOCUSING" : "READY WHEN YOU ARE"}</span><strong>{timeLabel}</strong><span>Pomodoro session · 25 minutes</span></div><div className="timer-actions"><button className="timer-main" onClick={onToggle}>{running ? "Pause session" : timer < 25 * 60 ? "Resume session" : "Start session"} <span>{running ? "Ⅱ" : "▶"}</span></button><button className="reset-button" onClick={onReset}>↻</button></div><button className="complete-session" onClick={onComplete} disabled={running}>Mark session complete</button><div className="timer-meta"><span><i className="live-dot" /> {running ? "Session in progress" : "Ready to begin"}</span><span>Sessions are saved locally</span></div></section>; }
function PlannerPanel({ week, selectedDay, setSelectedDay, tasks, planner }: { week: { key: string; label: string; date: number }[]; selectedDay: string; setSelectedDay: (day: string) => void; tasks: Task[]; planner: PlannerData }) { return <section className="panel planner-panel"><SectionHeading eyebrow="PLAN YOUR WEEK" title="Study planner" /><div className="week-grid">{week.map((item) => { const dayTasks = tasks.filter((task) => task.date === item.key); const minutes = dayTasks.reduce((sum, task) => sum + task.plannedMinutes, 0) + (planner[item.key]?.minutes ?? 0); return <button className={`day-column ${selectedDay === item.key ? "active" : ""}`} key={item.key} onClick={() => setSelectedDay(item.key)}><span className="day-name">{item.label}</span><strong>{item.date}</strong><div className="bar-track"><i style={{ height: `${Math.min(Math.max(minutes / 5, 12), 76)}px` }} /></div><span className="day-hours">{minutes ? `${Math.round(minutes / 60 * 10) / 10}h` : "—"}</span></button>; })}</div><div className="planner-footer"><span><i className="legend-dot" /> Planned study</span><span><strong>{tasks.filter((task) => week.some((day) => day.key === task.date)).reduce((sum, task) => sum + task.plannedMinutes, 0)} min</strong> planned this week</span></div></section>; }
function StatsPanel({ completionRate, sessions }: { completionRate: number; sessions: FocusSession[] }) { const bars = Array.from({ length: 7 }, (_, index) => { const day = new Date(); day.setDate(day.getDate() - (6 - index)); const key = dateKey(day); return sessions.filter((session) => session.completedAt.slice(0, 10) === key).reduce((sum, session) => sum + session.durationMinutes, 0); }); const max = Math.max(...bars, 25); return <section className="panel stats-panel"><SectionHeading eyebrow="YOUR MOMENTUM" title="Productivity" /><div className="productivity-body"><ProgressRing value={completionRate} /><div className="productivity-copy"><strong>{completionRate ? "Keep building" : "Your rhythm starts here"}</strong><p>{completionRate ? `${completionRate}% of your saved tasks are complete.` : "Complete a task or focus session to see your momentum."}</p><div className="trend">{sessions.length} <span>completed sessions</span></div></div></div><div className="mini-bars">{bars.map((value, index) => <span className={index === 6 ? "bar-today" : ""} style={{ height: `${Math.max(value / max * 100, value ? 14 : 4)}%` }} key={index} />)}</div></section>; }
function AISection() { return <section className="ai-section"><div className="ai-glow" /><div className="ai-copy"><div className="ai-badge">✦ STUDYFORGE AI <span>PLANNED</span></div><h2>A smarter study plan is <em>coming.</em></h2><p>AI guidance is on the roadmap. Until then, StudyForge keeps your tasks, schedule, and focus history honest and entirely in your hands.</p><button disabled>AI planning coming soon <span>→</span></button></div><div className="ai-orbit"><div className="orbit-card card-one">✦<span>Learn smarter</span></div><div className="orbit-card card-two">◷<span>Stay focused</span></div><div className="ai-core">✦</div></div></section>; }
function Settings({ name, setName, theme, setTheme }: { name: string; setName: (name: string) => void; theme: "light" | "warm"; setTheme: (theme: "light" | "warm") => void }) { const [draft, setDraft] = useState(name); return <section className="panel full-panel settings-page"><SectionHeading eyebrow="YOUR PREFERENCES" title="Settings" /><div className="settings-group"><label>Display name<span>Shown across your StudyForge workspace.</span></label><div className="settings-input"><input value={draft} onChange={(event) => setDraft(event.target.value)} /><button onClick={() => setName(draft.trim() || "Student")}>Save name</button></div></div><div className="settings-group"><label>Workspace tone<span>Choose the backdrop that helps you settle in.</span></label><div className="theme-options"><button className={theme === "light" ? "selected" : ""} onClick={() => setTheme("light")}>Light <span>Bright and clear</span></button><button className={theme === "warm" ? "selected" : ""} onClick={() => setTheme("warm")}>Warm <span>Soft and focused</span></button></div></div><p className="settings-note">Your preferences and activity are stored locally in this browser. No account or server is connected.</p></section>; }
